### ISSUE TITLE
关于这个项目的开源许可证

### ISSUE THREAD

**Issue by PandaDecSt** [moewhite19/about#2]
大佬, 你好丫.
我想把这个主题应用在我的网站上, 
但是没有得到许可我不敢乱来. 所以我想问一下这个项目的开源许可是怎么样的.

**Comment by PandaDecSt** [comment]
这个主题太棒了
(σﾟ∀ﾟ)σ⁶⁶⁶⁶⁶⁶⁶⁶⁶⁶

**Comment by moewhite19** [comment]
没所谓了
保留最底端的开发者名单就好了

**Comment by PandaDecSt** [comment]
好的
谢谢😂
